### ISSUE TITLE
Add Serious mode to create somewhat coherent recipes

### ISSUE THREAD

**Issue by gabLaroche** [gabLaroche/recipe-ipsum#11]
Sometimes recipes only contain spices or a single type of ingredient, it produces funny results, but it would be nice to have a "Serious Mode" where the measurement made sense for a certain type of ingredient and the types of ingredients would be varied in the recipe.

**Comment by Brainshaker95** [comment]
I will give it a go if that's okay

**Comment by gabLaroche** [comment]
@Brainshaker95 Yes! I assigned it to you!

**Comment by Brainshaker95** [comment]
#13

**Comment by Brainshaker95** [comment]
Making sense of the measurements is something I didn't implement yet. Maybe someone else could give it a shot
