### ISSUE TITLE
Numbers are not copied when copying recipe directions

### ISSUE THREAD

**Issue by gabLaroche** [gabLaroche/recipe-ipsum#18]
**Describe the bug**
Numbers are not copied when copying recipe directions
[See this comment](https://github.com/gabLaroche/recipe-ipsum/issues/6#issuecomment-702440517)

**To Reproduce**
1. Go to [recipe-ipsum.com](https://recipe-ipsum.com)
2. Click on 'Generate recipe'
3. Click on 'Copy directions to clipboard'
4. paste directions somewhere, notice that the numbers are not there

**Expected behavior**
Numbers should be pasted with directions

**Additional context**
I suggest that we apply `list-style-type: none;` on `.recipe__steps ol` and add a span with the number. It might be a good

**Comment by sylvaindessureault** [comment]
If nobody grabs this, I'd be glad to help!
